modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="obsidian_gear"
version="v1.0.0"
displayName="Obsidian Gear"
credits="Created by SniperNation317 (thesnipercitation#9118 is the discord)"
displayURL="https://snipernation.github.io/index.html"
logoFile="logo.png"
authors="SniperNation317"
description='''
Add obsidian gear like armor, tools and weapons as well as custom enchantments, biomes and blocks to your game!
'''

[[dependencies.obsidian_gear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




